#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: youyisi
disqus_show_comment_count: true

# site
title: youyisi's blog
url: http://youyisi.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: youyisi
author_email: zslangle86@gmail.com
author_info: <a href="http://haoyouyisi.github.com">youyisi</a>
